keys:
  - &mark age1vsgvskpnvyqwqfcqkmn5vnjxxpv67ztsxvh0g6pfp28kvwzfluqqytvpye
  - &hass age1v7ss7jz62lxd9f0zfw8hd8rk9sdpwwg8cmfzwwkx5efhpfpdxfwsff8sph
  - &moria age1s3e67gnktmu8qajw3hh7c4v6a22l9knw6c5pp0tk34kupvvem3fslwc3g6
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *mark
        - *hass
        - *moria
