name: Home

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        home: ['mark@mark-g15']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Set up Nix ❄️"
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Build home configuration 🏠"
        run: nix build .#homeConfigurations.${{ matrix.home }}.activationPackage

  darwin:
    name: Darwin
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        home: ['marksk@MARKSK-M-J1W8']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Set up Nix ❄️"
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Build home configuration 🏠"
        run: nix build .#homeConfigurations.${{ matrix.home }}.activationPackage
