name: System

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        host: ["mark-desktop", "mark-g15", "mark-x1carbon9", "moria"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up Nix ❄️"
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Set up Cachix ❄️"
        uses: cachix/cachix-action@v13
        with:
          name: skm-nixos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS config ❄️"
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel

  darwin:
    name: Darwin
    runs-on: macos-13

    strategy:
      fail-fast: false
      matrix:
        host: ["MARKSK-M-1WLF"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up Nix ❄️"
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: "Set up Cachix ❄️"
        uses: cachix/cachix-action@v13
        with:
          name: skm-nixos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build Darwin config ❄️"
        run: nix build .#darwinConfigurations.${{ matrix.host }}.config.system.build.toplevel
